language: php
dist: xenial
notifications:
  email:
    recipients:
      - kschwarz@hexonet.net
    on_success: never
    on_failure: always
php:
  - "7.3"
  - "7.4"
addons:
  apt:
    update: true
    packages:
      - graphviz
before_install:
  - export PATH="$HOME/.config/composer/vendor/bin:$PATH"
install:
  - travis_retry composer update
  - travis_retry composer global require phpunit/phpunit phpstan/phpstan dealerdirect/phpcodesniffer-composer-installer roave/security-advisories:dev-master squizlabs/php_codesniffer phpcompatibility/php-compatibility
script:
  - composer run-script phpStan
  - composer run-script phpCompatibility
  - composer run-script codeCheck
  - composer run-script test
jobs:
  include:
    - stage: release
      node_js: lts/*
      install:
        - rm -rf ~/.nvm
        - git clone https://github.com/creationix/nvm.git ~/.nvm
        - (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`)
        - source ~/.nvm/nvm.sh
        - nvm install lts/*
      script:
        - npm prune
        - travis_retry npm i
        - npx semantic-release
