version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    commit_message:
      prefix: "chore"

  - package_manager: "php:composer"
    directory: "/"
    update_schedule: "daily"
    commit_message:
      prefix: "chore"
